import jsPDF from "jspdf"

interface Activity {
  time?: string
  title: string
  category: string
}

interface DayPlan {
  day: number
  title?: string
  activities: Activity[]
}

interface TripData {
  destination: string
  duration: number
  difficulty?: string
  days: DayPlan[]
}

interface BackendDay {
  dia?: number
  day?: number
  resumen?: string
  summary?: string
  actividades?: any[]
  activities?: any[]
}

const COLORS = {
  primary: { r: 239, g: 68, b: 68 },
  primaryLight: { r: 254, g: 242, b: 242 },
  white: { r: 255, g: 255, b: 255 },
  dark: { r: 28, g: 28, b: 28 },
  darkGray: { r: 64, g: 64, b: 64 },
  gray: { r: 107, g: 114, b: 128 },
  grayLight: { r: 249, g: 250, b: 251 },
  grayMedium: { r: 229, g: 231, b: 235 },
  categories: {
    Culture: { r: 239, g: 68, b: 68, bg: { r: 254, g: 242, b: 242 } },
    Food: { r: 234, g: 88, b: 12, bg: { r: 254, g: 243, b: 235 } },
    Hiking: { r: 34, g: 197, b: 94, bg: { r: 240, g: 253, b: 244 } },
    Relaxation: { r: 59, g: 130, b: 246, bg: { r: 239, g: 246, b: 255 } },
    Sightseeing: { r: 217, g: 119, b: 6, bg: { r: 254, g: 252, b: 232 } },
    General: { r: 109, g: 40, b: 217, bg: { r: 245, g: 243, b: 255 } },
  } as Record<
    string,
    { r: number; g: number; b: number; bg: { r: number; g: number; b: number } }
  >,
}

const PAGE = {
  width: 210,
  height: 297,
  marginX: 20,
  marginY: 20,
  spacing: 10,
  get contentWidth() {
    return this.width - this.marginX * 2
  },
}

function truncateText(text: string, maxLength: number): string {
  if (!text) return ""
  return text.length > maxLength ? text.substring(0, maxLength - 3) + "..." : text
}

function drawHeader(doc: jsPDF, tripData: TripData): number {
  const headerHeight = 60
  const { marginX } = PAGE

  doc.setFillColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b)
  doc.rect(0, 0, PAGE.width, headerHeight, "F")

  doc.setFont("helvetica", "bold")
  doc.setFontSize(26)
  doc.setTextColor(255, 255, 255)
  doc.text("RutaÑ", marginX, 22)

  doc.setFont("helvetica", "normal")
  doc.setFontSize(9)
  doc.setTextColor(255, 230, 230)
  doc.text("Your AI Travel Companion", marginX, 32)

  const cardY = 38
  const cardH = 20
  doc.setFillColor(COLORS.white.r, COLORS.white.g, COLORS.white.b)
  doc.roundedRect(marginX, cardY, PAGE.contentWidth, cardH, 4, 4, "F")

  doc.setFont("helvetica", "bold")
  doc.setFontSize(12)
  doc.setTextColor(COLORS.dark.r, COLORS.dark.g, COLORS.dark.b)
  doc.text(
    truncateText(tripData.destination || "Destination", 36),
    marginX + 12,
    cardY + 13
  )

  const badgeW = 34
  const badgeX = PAGE.width - marginX - badgeW
  doc.setFillColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b)
  doc.roundedRect(badgeX, cardY + 4, badgeW, 12, 3, 3, "F")
  doc.setFont("helvetica", "bold")
  doc.setFontSize(8)
  doc.setTextColor(COLORS.white.r, COLORS.white.g, COLORS.white.b)
  doc.text(`${tripData.duration}d`, badgeX + badgeW / 2, cardY + 12, {
    align: "center",
  })

  doc.setFont("helvetica", "normal")
  doc.setFontSize(7)
  doc.setTextColor(COLORS.gray.r, COLORS.gray.g, COLORS.gray.b)
  doc.text(
    (tripData.difficulty || "Explorer").substring(0, 20),
    badgeX - 4,
    cardY + 12,
    { align: "right" }
  )

  return headerHeight + 10
}

function drawSectionTitle(doc: jsPDF, title: string, y: number): number {
  doc.setFillColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b)
  doc.roundedRect(PAGE.marginX, y, 3, 10, 1, 1, "F")

  doc.setFont("helvetica", "bold")
  doc.setFontSize(12)
  doc.setTextColor(COLORS.dark.r, COLORS.dark.g, COLORS.dark.b)
  doc.text(title, PAGE.marginX + 9, y + 8)

  return y + 16
}

function drawContinuationHeader(doc: jsPDF): number {
  doc.setFont("helvetica", "bold")
  doc.setFontSize(11)
  doc.setTextColor(COLORS.gray.r, COLORS.gray.g, COLORS.gray.b)
  doc.text("Itinerary (continued)", PAGE.marginX, PAGE.marginY + 8)

  doc.setDrawColor(COLORS.grayMedium.r, COLORS.grayMedium.g, COLORS.grayMedium.b)
  doc.setLineWidth(0.3)
  doc.line(PAGE.marginX, PAGE.marginY + 12, PAGE.marginX + 55, PAGE.marginY + 12)

  return PAGE.marginY + 20
}

function drawFooter(doc: jsPDF, pageNum: number, totalPages: number): void {
  const y = PAGE.height - 15

  doc.setDrawColor(COLORS.grayMedium.r, COLORS.grayMedium.g, COLORS.grayMedium.b)
  doc.setLineWidth(0.3)
  doc.line(PAGE.marginX, y - 6, PAGE.width - PAGE.marginX, y - 6)

  doc.setFont("helvetica", "normal")
  doc.setFontSize(8)
  doc.setTextColor(COLORS.gray.r, COLORS.gray.g, COLORS.gray.b)
  doc.text("Generated by RutaÑ AI", PAGE.marginX, y)

  doc.text(`Page ${pageNum} of ${totalPages}`, PAGE.width / 2, y, {
    align: "center",
  })

  doc.setFont("helvetica", "bold")
  doc.setTextColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b)
  doc.text("rutañ.ai", PAGE.width - PAGE.marginX, y, { align: "right" })
}

/**
 * Layout común del encabezado de la tarjeta de día
 */
function computeDayHeaderLayout(doc: jsPDF, day: DayPlan) {
  const paddingX = 12
  const cardWidth = PAGE.contentWidth
  const headerBase = 18

  // Badge "Day X"
  doc.setFont("helvetica", "bold")
  doc.setFontSize(8)
  const dayBadgeText = `Day ${day.day}`
  const dayBadgeW = Math.min(Math.max(24, doc.getTextWidth(dayBadgeText) + 10), 48)

  const titleX = PAGE.marginX + paddingX + dayBadgeW + 8
  const titleMaxWidth = cardWidth - (titleX - PAGE.marginX) - paddingX

  doc.setFont("helvetica", "normal")
  doc.setFontSize(9)
  const titleLines = doc.splitTextToSize(day.title || "", titleMaxWidth)
  const lineHeight = 4.5
  const titleExtra = Math.max(0, (titleLines.length - 1) * lineHeight)
  const headerHeight = headerBase + titleExtra

  return { headerHeight, dayBadgeW, titleLines, titleX, lineHeight }
}

/**
 * Altura estimada de la tarjeta, consistente con drawDayCard
 */
function estimateDayCardHeight(day: DayPlan): number {
  const paddingY = 8
  const activitySpacing = 6

  const doc = new jsPDF({ unit: "mm", format: "a4" })
  const cardWidth = PAGE.contentWidth
  const paddingX = 12

  const { headerHeight } = computeDayHeaderLayout(doc, day)

  let activitiesH = 0

  for (const a of day.activities) {
    const title = a?.title || ""
    const timeText = (a?.time || "").toUpperCase().substring(0, 8) || "00:00"

    // ancho columna hora
    doc.setFont("helvetica", "bold")
    doc.setFontSize(7)
    const timeW = Math.max(12, doc.getTextWidth(timeText) + 4)

    // ancho pill categoría
    const catText = a?.category || "General"
    doc.setFont("helvetica", "bold")
    doc.setFontSize(7)
    const rawBadgeW = doc.getTextWidth(catText) + 6
    const badgeW = Math.min(Math.max(18, rawBadgeW), 48)

    // ancho de texto entre hora y pill
    const textX = PAGE.marginX + paddingX + timeW + 4
    const textRight = PAGE.marginX + cardWidth - paddingX - badgeW - 4
    const textWidth = Math.max(20, textRight - textX)

    doc.setFont("helvetica", "normal")
    doc.setFontSize(8)
    const wrapped = doc.splitTextToSize(title, textWidth)
    const activityLineHeight = 4.5
    const activityH = Math.max(10, wrapped.length * activityLineHeight)

    activitiesH += activityH + activitySpacing
  }

  const total = paddingY * 2 + headerHeight + activitiesH
  return Math.max(total, 40)
}

/**
 * Dibujo real de la tarjeta de día
 */
function drawDayCard(doc: jsPDF, day: DayPlan, y: number): number {
  const paddingX = 12
  const paddingY = 8
  const activitySpacing = 6
  const cardWidth = PAGE.contentWidth

  const cardHeight = estimateDayCardHeight(day)

  const { headerHeight, dayBadgeW, titleLines, titleX, lineHeight } =
    computeDayHeaderLayout(doc, day)

  // Sombra
  doc.setFillColor(240, 240, 240)
  doc.setDrawColor(0, 0, 0)
  doc.setLineWidth(0)
  doc.roundedRect(PAGE.marginX + 1, y + 1, cardWidth, cardHeight, 5, 5, "F")

  // Tarjeta principal
  doc.setFillColor(COLORS.white.r, COLORS.white.g, COLORS.white.b)
  doc.setDrawColor(COLORS.grayMedium.r, COLORS.grayMedium.g, COLORS.grayMedium.b)
  doc.setLineWidth(0.3)
  doc.roundedRect(PAGE.marginX, y, cardWidth, cardHeight, 5, 5, "FD")

  // Header rosado
  doc.setFillColor(COLORS.primaryLight.r, COLORS.primaryLight.g, COLORS.primaryLight.b)
  doc.roundedRect(PAGE.marginX, y, cardWidth, headerHeight, 4, 4, "F")

  // Badge "Day X"
  const dayBadgeX = PAGE.marginX + paddingX
  const dayBadgeY = y + 4
  const dayBadgeH = 11

  doc.setFillColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b)
  doc.roundedRect(dayBadgeX, dayBadgeY, dayBadgeW, dayBadgeH, 2, 2, "F")

  doc.setFont("helvetica", "bold")
  doc.setFontSize(8)
  doc.setTextColor(COLORS.white.r, COLORS.white.g, COLORS.white.b)
  doc.text(
    `Day ${day.day}`,
    dayBadgeX + dayBadgeW / 2,
    dayBadgeY + dayBadgeH / 2 + 2,
    { align: "center" }
  )

  // Título del día
  doc.setFont("helvetica", "normal")
  doc.setFontSize(9)
  doc.setTextColor(COLORS.darkGray.r, COLORS.darkGray.g, COLORS.darkGray.b)

  const titleStartY = y + 11
  titleLines.forEach((line: string, idx: number) => {
    doc.text(line, titleX, titleStartY + idx * lineHeight)
  })

  // Actividades
  let cursorY = y + headerHeight + paddingY

  for (let idx = 0; idx < day.activities.length; idx++) {
    const activity = day.activities[idx]
    const title = activity.title || ""
    const timeText = (activity.time || "").toUpperCase().substring(0, 8) || "00:00"
    const cat = COLORS.categories[activity.category] || COLORS.categories.General
    const catText = activity.category || "General"

    // ancho hora
    doc.setFont("helvetica", "bold")
    doc.setFontSize(7)
    doc.setTextColor(COLORS.gray.r, COLORS.gray.g, COLORS.gray.b)
    const timeW = Math.max(12, doc.getTextWidth(timeText) + 4)

    // ancho pill categoría
    doc.setFont("helvetica", "bold")
    doc.setFontSize(7)
    const rawBadgeW = doc.getTextWidth(catText) + 6
    const badgeW = Math.min(Math.max(18, rawBadgeW), 48)

    const rowY = cursorY

    // ancho texto entre hora y pill
    const textX = PAGE.marginX + paddingX + timeW + 4
    const textRight = PAGE.marginX + cardWidth - paddingX - badgeW - 4
    const textWidth = Math.max(20, textRight - textX)

    doc.setFont("helvetica", "normal")
    doc.setFontSize(8)
    doc.setTextColor(COLORS.dark.r, COLORS.dark.g, COLORS.dark.b)
    const wrapped = doc.splitTextToSize(title, textWidth)
    const activityLineHeight = 4.5
    const activityH = Math.max(10, wrapped.length * activityLineHeight)

    // Fila de fondo alterna
    if (idx % 2 === 0) {
      doc.setFillColor(COLORS.grayLight.r, COLORS.grayLight.g, COLORS.grayLight.b)
      doc.roundedRect(
        PAGE.marginX + 6,
        rowY - 4,
        cardWidth - 12,
        activityH + 8,
        3,
        3,
        "F"
      )
    }

    // Hora
    doc.setFont("helvetica", "bold")
    doc.setFontSize(7)
    doc.setTextColor(COLORS.gray.r, COLORS.gray.g, COLORS.gray.b)
    doc.text(timeText, PAGE.marginX + paddingX, rowY + 2)

    // Texto actividad
    doc.setFont("helvetica", "normal")
    doc.setFontSize(8)
    doc.setTextColor(COLORS.dark.r, COLORS.dark.g, COLORS.dark.b)
    wrapped.forEach((line: string, i: number) => {
      doc.text(line, textX, rowY + 2 + i * activityLineHeight)
    })

    // Pill categoría
    const badgeX = PAGE.marginX + cardWidth - paddingX - badgeW
    const badgeY = rowY - 3
    const badgeH = 12

    doc.setFillColor(cat.bg.r, cat.bg.g, cat.bg.b)
    doc.roundedRect(badgeX, badgeY, badgeW, badgeH, 3, 3, "F")

    doc.setFont("helvetica", "bold")
    doc.setFontSize(7)
    doc.setTextColor(cat.r, cat.g, cat.b)
    doc.text(catText, badgeX + badgeW / 2, badgeY + badgeH / 2 + 1.5, {
      align: "center",
    })

    cursorY += activityH + activitySpacing
  }

  const usedHeight = Math.max(cardHeight, cursorY - y + paddingY)
  return usedHeight
}

function fitsInPage(nextHeight: number, currentY: number) {
  return currentY + nextHeight < PAGE.height - 30
}

function normalizeCategoryToString(cat: any): string {
  if (!cat) return "General"
  const s = String(cat).toLowerCase()
  const categoryMap: Record<string, string> = {
    cultur: "Culture",
    food: "Food",
    gastr: "Food",
    tapa: "Food",
    hik: "Hiking",
    trek: "Hiking",
    relax: "Relaxation",
    sight: "Sightseeing",
    tour: "Sightseeing",
    general: "General",
  }
  for (const [key, value] of Object.entries(categoryMap)) {
    if (s.includes(key)) return value
  }
  return "General"
}

export function convertBackendToTripData(
  destination: string,
  duration: number,
  backendDays: any[]
): TripData {
  const days: DayPlan[] = backendDays.map((d: any, idx: number) => {
    const dayNum = d?.dia || d?.day || idx + 1
    const resumen = (d?.resumen || d?.summary || "").trim()
    const actividades = d?.actividades || d?.activities || d?.itinerario || []

    const activities: Activity[] = (actividades || []).map((a: any) => {
      const isString = typeof a === "string"
      const text = isString
        ? a
        : a.activity || a.nombre || a.name || a.title || String(a)
      const rawCat =
        !isString && typeof a === "object"
          ? a.category || a.categoria || a.type
          : undefined
      const category = normalizeCategoryToString(rawCat)
      const time =
        !isString && (a?.time || a?.hora) ? String(a?.time || a?.hora) : ""
      const momento = !isString && a?.momento ? String(a?.momento) : ""
      const detalles =
        !isString && (a?.detalles || a?.details)
          ? String(a?.detalles || a?.details)
          : ""

      let composedTitle = String(text || "Activity")
      if (momento && !time) {
        composedTitle = `${momento} · ${composedTitle}`
      }
      if (detalles) {
        composedTitle = `${composedTitle} — ${detalles}`
      }

      return {
        time,
        title: composedTitle,
        category,
      }
    })

    return {
      day: Number(dayNum),
      title: resumen ? String(resumen).substring(0, 80) : `Day ${idx + 1}`,
      activities,
    }
  })

  return {
    destination,
    duration,
    difficulty: "Explorer",
    days,
  }
}

export function generateItineraryPDFFromBackend(
  destination: string,
  duration: number,
  backendDays: any[]
): void {
  const tripData = convertBackendToTripData(destination, duration, backendDays)
  return generateItineraryPDF(tripData)
}

export function generateItineraryPDF(tripData: TripData): void {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  })

  // Pre-cálculo de páginas
  let tempY = 0
  let tempPages = 1
  const headerH = 60 + 10
  tempY = headerH
  tempY = drawSectionTitlePlaceholder(tempY)

  for (const day of tripData.days) {
    const cardH = estimateDayCardHeight(day) + PAGE.spacing
    if (!fitsInPage(cardH, tempY)) {
      tempPages++
      tempY = PAGE.marginY + 20
    }
    tempY += cardH
  }

  const totalPages = tempPages

  // Render real
  let currentY = drawHeader(doc, tripData)
  let currentPage = 1

  currentY = drawSectionTitle(doc, "Your Complete Itinerary", currentY)

  for (const day of tripData.days) {
    const cardH = estimateDayCardHeight(day) + PAGE.spacing

    if (!fitsInPage(cardH, currentY)) {
      drawFooter(doc, currentPage, totalPages)
      doc.addPage()
      currentPage++
      currentY = drawContinuationHeader(doc)
    }

    const realH = drawDayCard(doc, day, currentY)
    currentY += realH + PAGE.spacing
  }

  drawFooter(doc, currentPage, totalPages)

  const safeDestination = (tripData.destination || "trip")
    .replace(/\s+/g, "_")
    .replace(/[^\w\-_.]/g, "")
  const fileName = `RutaÑ_${safeDestination}_${tripData.duration}days.pdf`
  doc.save(fileName)
}

function drawSectionTitlePlaceholder(y: number) {
  return y + 16
}

export type { TripData, DayPlan, Activity, BackendDay }
