import jsPDF from "jspdf"

interface Activity {
  time?: string
  title: string
  category: string
}

interface DayPlan {
  day: number
  title?: string
  activities: Activity[]
}

interface TripData {
  destination: string
  duration: number
  difficulty?: string
  days: DayPlan[]
}

interface BackendDay {
  dia?: number
  day?: number
  resumen?: string
  summary?: string
  actividades?: any[]
  activities?: any[]
}

const COLORS = {
  primary: { r: 239, g: 68, b: 68 },
  primaryLight: { r: 254, g: 242, b: 242 },
  white: { r: 255, g: 255, b: 255 },
  dark: { r: 28, g: 28, b: 28 },
  darkGray: { r: 64, g: 64, b: 64 },
  gray: { r: 107, g: 114, b: 128 },
  grayLight: { r: 249, g: 250, b: 251 },
  grayMedium: { r: 229, g: 231, b: 235 },
  categories: {
    Culture: { r: 239, g: 68, b: 68, bg: { r: 254, g: 242, b: 242 } },
    Food: { r: 234, g: 88, b: 12, bg: { r: 254, g: 243, b: 235 } },
    Hiking: { r: 34, g: 197, b: 94, bg: { r: 240, g: 253, b: 244 } },
    Relaxation: { r: 59, g: 130, b: 246, bg: { r: 239, g: 246, b: 255 } },
    Sightseeing: { r: 217, g: 119, b: 6, bg: { r: 254, g: 252, b: 232 } },
    General: { r: 109, g: 40, b: 217, bg: { r: 245, g: 243, b: 255 } },
  } as Record<string, { r: number; g: number; b: number; bg: { r: number; g: number; b: number } }>,
}

const PAGE = {
  width: 210,
  height: 297,
  marginX: 20,
  marginY: 20,
  spacing: 10,
  get contentWidth() {
    return this.width - this.marginX * 2
  },
}

function truncateText(text: string, maxLength: number): string {
  if (!text) return ""
  return text.length > maxLength ? text.substring(0, maxLength - 3) + "..." : text
}

function drawHeader(doc: jsPDF, tripData: TripData): number {
  const headerHeight = 60
  const { marginX } = PAGE

  doc.setFillColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b)
  doc.rect(0, 0, PAGE.width, headerHeight, "F")

  doc.setFont("helvetica", "bold")
  doc.setFontSize(26)
  doc.setTextColor(255, 255, 255)
  doc.text("RutaÑ", marginX, 22)

  doc.setFont("helvetica", "normal")
  doc.setFontSize(9)
  doc.setTextColor(255, 230, 230)
  doc.text("Your AI Travel Companion", marginX, 32)

  const cardY = 38
  const cardH = 20
  doc.setFillColor(COLORS.white.r, COLORS.white.g, COLORS.white.b)
  doc.roundedRect(marginX, cardY, PAGE.contentWidth, cardH, 4, 4, "F")

  doc.setFont("helvetica", "bold")
  doc.setFontSize(12)
  doc.setTextColor(COLORS.dark.r, COLORS.dark.g, COLORS.dark.b)
  doc.text(truncateText(tripData.destination || "Destination", 36), marginX + 12, cardY + 13)

  const badgeW = 34
  const badgeX = PAGE.width - marginX - badgeW
  doc.setFillColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b)
  doc.roundedRect(badgeX, cardY + 4, badgeW, 12, 3, 3, "F")
  doc.setFont("helvetica", "bold")
  doc.setFontSize(8)
  doc.setTextColor(COLORS.white.r, COLORS.white.g, COLORS.white.b)
  doc.text(`${tripData.duration}d`, badgeX + badgeW / 2, cardY + 12, { align: "center" })

  doc.setFont("helvetica", "normal")
  doc.setFontSize(7)
  doc.setTextColor(COLORS.gray.r, COLORS.gray.g, COLORS.gray.b)
  doc.text((tripData.difficulty || "Explorer").substring(0, 20), badgeX - 4, cardY + 12, { align: "right" })

  return headerHeight + 10
}

function drawSectionTitle(doc: jsPDF, title: string, y: number): number {
  doc.setFillColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b)
  doc.roundedRect(PAGE.marginX, y, 3, 10, 1, 1, "F")

  doc.setFont("helvetica", "bold")
  doc.setFontSize(12)
  doc.setTextColor(COLORS.dark.r, COLORS.dark.g, COLORS.dark.b)
  doc.text(title, PAGE.marginX + 9, y + 8)

  return y + 16
}

function drawContinuationHeader(doc: jsPDF): number {
  doc.setFont("helvetica", "bold")
  doc.setFontSize(11)
  doc.setTextColor(COLORS.gray.r, COLORS.gray.g, COLORS.gray.b)
  doc.text("Itinerary (continued)", PAGE.marginX, PAGE.marginY + 8)

  doc.setDrawColor(COLORS.grayMedium.r, COLORS.grayMedium.g, COLORS.grayMedium.b)
  doc.setLineWidth(0.3)
  doc.line(PAGE.marginX, PAGE.marginY + 12, PAGE.marginX + 55, PAGE.marginY + 12)

  return PAGE.marginY + 20
}

function drawFooter(doc: jsPDF, pageNum: number, totalPages: number): void {
  const y = PAGE.height - 15

  doc.setDrawColor(COLORS.grayMedium.r, COLORS.grayMedium.g, COLORS.grayMedium.b)
  doc.setLineWidth(0.3)
  doc.line(PAGE.marginX, y - 6, PAGE.width - PAGE.marginX, y - 6)

  doc.setFont("helvetica", "normal")
  doc.setFontSize(8)
  doc.setTextColor(COLORS.gray.r, COLORS.gray.g, COLORS.gray.b)
  doc.text("Generated by RutaÑ AI", PAGE.marginX, y)

  doc.text(`Page ${pageNum} of ${totalPages}`, PAGE.width / 2, y, { align: "center" })

  doc.setFont("helvetica", "bold")
  doc.setTextColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b)
  doc.text("rutañ.ai", PAGE.width - PAGE.marginX, y, { align: "right" })
}

function estimateDayCardHeight(day: DayPlan): number {
  const paddingY = 8
  const headerHeight = 18
  const activityBase = 14
  const activitySpacing = 6
  const activitiesH = day.activities.length * (activityBase + activitySpacing)
  const minTitleLines = Math.ceil((truncateText(day.title || "", 70).length || 0) / 40)
  const titleExtra = Math.max(0, (minTitleLines - 1) * 5)
  const total = paddingY * 2 + headerHeight + activitiesH + titleExtra
  return total
}

function drawDayCard(doc: jsPDF, day: DayPlan, y: number): number {
  const paddingX = 12
  const paddingY = 8
  const headerHeight = 18
  const activityBase = 14
  const activitySpacing = 6
  const cardWidth = PAGE.contentWidth

  const cardHeight = estimateDayCardHeight(day)

  doc.setFillColor(0, 0, 0)
  doc.setDrawColor(0, 0, 0)
  doc.setLineWidth(0)
  doc.setFillColor(240, 240, 240)
  doc.roundedRect(PAGE.marginX + 1, y + 1, cardWidth, cardHeight, 5, 5, "F")

  doc.setFillColor(COLORS.white.r, COLORS.white.g, COLORS.white.b)
  doc.setDrawColor(COLORS.grayMedium.r, COLORS.grayMedium.g, COLORS.grayMedium.b)
  doc.setLineWidth(0.3)
  doc.roundedRect(PAGE.marginX, y, cardWidth, cardHeight, 5, 5, "FD")

  doc.setFillColor(COLORS.primaryLight.r, COLORS.primaryLight.g, COLORS.primaryLight.b)
  doc.roundedRect(PAGE.marginX, y, cardWidth, headerHeight, 4, 4, "F")

  doc.setFillColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b)
  doc.roundedRect(PAGE.marginX + paddingX, y + 3, 24, 11, 2, 2, "F")
  doc.setFont("helvetica", "bold")
  doc.setFontSize(8)
  doc.setTextColor(COLORS.white.r, COLORS.white.g, COLORS.white.b)
  doc.text(`Day ${day.day}`, PAGE.marginX + paddingX + 12, y + 11, { align: "center" })

  doc.setFont("helvetica", "normal")
  doc.setFontSize(9)
  doc.setTextColor(COLORS.darkGray.r, COLORS.darkGray.g, COLORS.darkGray.b)
  doc.text(truncateText(day.title || "", 70), PAGE.marginX + paddingX + 38, y + 12)

  let cursorY = y + headerHeight + paddingY

  const maxTitleLength = Math.max(0, ...day.activities.map((a) => (a.title ? a.title.length : 0)))
  const activityFontSize = maxTitleLength > 50 ? 7.5 : 8

  day.activities.forEach((activity, idx) => {
    const activityH = activityBase
    const rowY = cursorY

    if (idx % 2 === 0) {
      doc.setFillColor(COLORS.grayLight.r, COLORS.grayLight.g, COLORS.grayLight.b)
      doc.roundedRect(PAGE.marginX + 6, rowY - 4, cardWidth - 12, activityH + 6, 3, 3, "F")
    }

    doc.setFont("helvetica", "bold")
    doc.setFontSize(7)
    doc.setTextColor(COLORS.gray.r, COLORS.gray.g, COLORS.gray.b)
    const timeText = (activity.time || "").toUpperCase().substring(0, 8)
    doc.text(timeText, PAGE.marginX + paddingX, rowY + 3)

    doc.setFont("helvetica", "normal")
    doc.setFontSize(activityFontSize)
    doc.setTextColor(COLORS.dark.r, COLORS.dark.g, COLORS.dark.b)
    doc.text(truncateText(activity.title, 80), PAGE.marginX + paddingX + 22, rowY + 3)

    const cat = COLORS.categories[activity.category] || COLORS.categories.General
    const catText = activity.category || "General"
    const badgeW = Math.min(catText.length * 3 + 14, 60)
    const badgeX = PAGE.marginX + cardWidth - paddingX - badgeW

    doc.setFillColor(cat.bg.r, cat.bg.g, cat.bg.b)
    doc.roundedRect(badgeX, rowY - 5, badgeW, 12, 3, 3, "F")

    doc.setFont("helvetica", "bold")
    doc.setFontSize(7)
    doc.setTextColor(cat.r, cat.g, cat.b)
    doc.text(catText, badgeX + badgeW / 2, rowY + 3, { align: "center" })

    cursorY += activityH + activitySpacing
  })

  return cardHeight
}

function fitsInPage(nextHeight: number, currentY: number) {
  return currentY + nextHeight < PAGE.height - 30
}


function normalizeCategoryToString(cat: any): string {
  if (!cat) return "General"
  const s = String(cat).toLowerCase()
  const categoryMap: Record<string, string> = {
    cultur: "Culture",
    food: "Food",
    gastr: "Food",
    tapa: "Food",
    hik: "Hiking",
    trek: "Hiking",
    relax: "Relaxation",
    sight: "Sightseeing",
    tour: "Sightseeing",
    general: "General",
  }
  for (const [key, value] of Object.entries(categoryMap)) {
    if (s.includes(key)) return value
  }
  return "General"
}

export function convertBackendToTripData(
  destination: string,
  duration: number,
  backendDays: any[]
): TripData {
  const days: DayPlan[] = backendDays.map((d: any, idx: number) => {
    const dayNum = d?.dia || d?.day || idx + 1
    const resumen = (d?.resumen || d?.summary || "").trim()
    const actividades = d?.actividades || d?.activities || []

    const activities: Activity[] = (actividades || []).map((a: any) => {
      const text = typeof a === "string" ? a : a.activity || a.nombre || a.name || a.title || "Activity"
      const rawCat = typeof a === "object" ? a.category || a.categoria || a.type : undefined
      const category = normalizeCategoryToString(rawCat)
      return {
        time: a?.time || a?.hora || "",
        title: String(text || "Activity"),
        category,
      }
    })

    return {
      day: Number(dayNum),
      title: resumen ? String(resumen).substring(0, 80) : `Day ${idx + 1}`,
      activities,
    }
  })

  return {
    destination,
    duration,
    difficulty: "Explorer",
    days,
  }
}


export function generateItineraryPDFFromBackend(
  destination: string,
  duration: number,
  backendDays: any[]
): void {
  const tripData = convertBackendToTripData(destination, duration, backendDays)
  return generateItineraryPDF(tripData)
}

export function generateItineraryPDF(tripData: TripData): void {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  })

  let tempY = 0
  let tempPages = 1
  const headerH = 60 + 10
  tempY = headerH
  tempY = drawSectionTitlePlaceholder(tempY) 

  for (const day of tripData.days) {
    const cardH = estimateDayCardHeight(day) + PAGE.spacing
    if (!fitsInPage(cardH, tempY)) {
      tempPages++
      tempY = PAGE.marginY + 20 
    }
    tempY += cardH
  }

  const totalPages = tempPages

  let currentY = drawHeader(doc, tripData)
  let currentPage = 1

  currentY = drawSectionTitle(doc, "Your Complete Itinerary", currentY)

  for (const day of tripData.days) {
    const cardH = estimateDayCardHeight(day) + PAGE.spacing

    if (!fitsInPage(cardH, currentY)) {
      drawFooter(doc, currentPage, totalPages)
      doc.addPage()
      currentPage++
      currentY = drawContinuationHeader(doc)
    }

    const realH = drawDayCard(doc, day, currentY)
    currentY += realH + PAGE.spacing
  }

  drawFooter(doc, currentPage, totalPages)

  const safeDestination = (tripData.destination || "trip").replace(/\s+/g, "_").replace(/[^\w\-_.]/g, "")
  const fileName = `RutaÑ_${safeDestination}_${tripData.duration}days.pdf`
  doc.save(fileName)
}

function drawSectionTitlePlaceholder(y: number) {
  return y + 16
}

export type { TripData, DayPlan, Activity, BackendDay }
